Senai.Chamados.Web/Controllers/ContaController.cs
using AutoMapper;
using Senai.Chamados.Data.Contexto;
using Senai.Chamados.Data.Repositorios;
using Senai.Chamados.Domain.Entidades;
using Senai.Chamados.Domain.Enum;
using Senai.Chamados.Web.Util;
using Senai.Chamados.Web.ViewModels;
using Senai.Chamados.Web.ViewModels.Usuario;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace Senai.Chamados.Web.Controllers
{
    public class ContaController : Controller
    {
        // GET: Conta
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel Login)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Erro = "Dados Inválidos";
                return View();
            }

            using(UsuarioRepositorio _repUsuario = new UsuarioRepositorio())
            {
                UsuarioDomain objUsuario = _repUsuario.Login(Login.Email, Hash.GerarHash(Login.Senha));

                if(objUsuario != null)
                {
                    var identity = new ClaimsIdentity(new[] {
                        new Claim(ClaimTypes.Name, objUsuario.Nome),
                        new Claim(ClaimTypes.Email, objUsuario.Email),
                        new Claim(ClaimTypes.NameIdentifier,objUsuario.Id.ToString()),
                        new Claim(ClaimTypes.Role, objUsuario.TipoUsuario.ToString()),
                        //Defini uma Claim com um novo tipo
                        new Claim("Telefone", objUsuario.Telefone.ToString())
                    }, "ApplicationCookie");

                    Request.GetOwinContext().Authentication.SignIn(identities: identity);

                    return RedirectToAction("Index", "Usuario");
                }
                else
                {
                    ViewBag.Erro = "Usuário ou senha inválidos. Tente novamente";
                    return View(Login);
                }
            }

        }

        [HttpGet]
        public ActionResult CadastrarUsuario()
        {
            UsuarioViewModel objCadastrarUsuario = new UsuarioViewModel();

            objCadastrarUsuario.ListaSexo =  ListaSexo();
            
            return View(objCadastrarUsuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarUsuario(UsuarioViewModel usuario)
        {
            usuario.ListaSexo = ListaSexo();

            if (!ModelState.IsValid)
            {
                ViewBag.Erro = "Dados inválidos";
                return View(usuario);
            }

            try
            {
                usuario.Cpf = usuario.Cpf.Replace(".", "").Replace("-","");
                usuario.Cep = usuario.Cep.Replace("-", "");
                usuario.TipoUsuario = EnTipoUsuario.Padrao;
                usuario.Senha = Hash.GerarHash(usuario.Senha);

                using(UsuarioRepositorio _repUsuario = new UsuarioRepositorio())
                {
                    _repUsuario.Inserir(Mapper.Map<UsuarioViewModel, UsuarioDomain>(usuario));
                }

                TempData["Mensagem"] = "Usuário cadastrado";
                return RedirectToAction("Login");
            }
            catch (System.Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View(usuario);
            }
        }

        private SelectList ListaSexo()
        {
            return new SelectList(
             new List<SelectListItem>
             {
              new SelectListItem { Text = "Masculino", Value = "1"},
              new SelectListItem { Text= "Feminino", Value = "2"},
             }, "Value", "Text");
        }

        [HttpGet]
        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut("ApplicationCookie");

            return RedirectToAction("Login");
        }
    }
}

Senai.Chamados.Web/Controllers/PerfilController.cs
using Senai.Chamados.Data.Repositorios;
using Senai.Chamados.Domain.Entidades;
using Senai.Chamados.Web.Util;
using Senai.Chamados.Web.ViewModels.Conta;
using System;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace Senai.Chamados.Web.Controllers
{
    [Authorize]
    public class PerfilController : Controller
    {
        // GET: Perfil
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AlterarSenha()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AlterarSenha(AlterarSenhaViewModel senha)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.Erro = "Dados inválidos. Verifique!";
                    return View();
                }

                //Obtêm as Claims do usuário logado
                var identity = User.Identity as ClaimsIdentity;
                //Pega o valor do Id do usuário
                var id = identity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
                //Obtêm o valor de uma Claim nâo definida
                var telefone = identity.Claims.FirstOrDefault(x => x.Type == "Telefone").Value;

                //Cria uma instancia de UsuarioRepositorio
                using(UsuarioRepositorio  objRepoUsuario = new UsuarioRepositorio())
                {
                    //Busca o usuário pelo seu Id
                    UsuarioDomain objUsuario = objRepoUsuario.BuscarPorId(new Guid(id));

                    //Verifico se a senha informada é igual a Atual
                    if(Hash.GerarHash(senha.SenhaAtual) != objUsuario.Senha)
                    {
                        //Senha inválida eu informo ao usuário
                        ModelState.AddModelError("SenhaAtual", "Senha incorreta");
                        return View();
                    }
                    //Atribuimos o valor da nova senha ao objeto usuário
                    objUsuario.Senha = Hash.GerarHash(senha.NovaSenha);
                    //Alteramos o usuário no banco
                    objRepoUsuario.Alterar(objUsuario);
                    //Definimos a mensagem que irá aparecer na tela
                    TempData["Sucesso"] = "Senha Alterada";
                    //Retornamos ao Controller Usuário, Index
                    return RedirectToAction("Index", "Usuario");
                }               
            }
            catch (System.Exception ex)
            {
                ViewBag.Erro = "Ocorreu um erro " + ex.Message;
                return View();
            }
        }
    }
}

Senai.Chamados.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Senai.Chamados.Web/Views/Shared/_LayoutPage.cshtml
@using Senai.Chamados.Web.Helpers
<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />

    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    Senai Chamados
                </a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">

                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="/Chamado" class="nav-item">Chamados</a>
                        </li>
                        if (User.IsInRole("Administrador"))
                        {
                        <li>
                            <a href="/Usuario" class="nav-item">Usuários</a>
                        </li>
                        }
                        <li>
                            <a href="/Graficos" class="nav-item">Gráficos</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item login">
                            <a class="nav-link " href="/conta/login">Login <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item cadastrarusuario">
                            <a class="nav-link" href="/conta/cadastrarusuario">Cadastrar Conta</a>
                        </li>
                    </ul>
                }

                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle nav-item" data-toggle="dropdown">@MeuHelper.BoasVindas() @User.Identity.Name<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Alterar Senha", "AlterarSenha", "Perfil")</li>
                                <li>@Html.ActionLink("Sair", "Logout", "Conta")</li>
                            </ul>
                        </li>
                    </ul>
                }
            </div><!--/.nav-collapse -->
        </div>
    </nav>


    <div class="container">

        @RenderBody()

        <hr />
        <footer>
            <p>@MeuHelper.DireitosReservados()</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>